### ISSUE TITLE
Potential NPE in InvocationExprent.appendParamList

### ISSUE THREAD

**Issue by SuperCoder7979** [MinecraftForge/ForgeFlower#93]
If a class that is being checked for overloaded unboxing is not found in the current context, likely due to libraries not being found on the classpath, a NullPointerException is thrown. The relevant code is here: https://github.com/MinecraftForge/ForgeFlower/blob/cc2014dec8c08049e9184a6b86cd3981f193f3de/FernFlower-Patches/0014-Fix-primitive-un-boxing-issues.patch#L189
Placing a null check before the loop creates no problems and the method decompiles fine.

**Comment by Geolykt** [comment]
I can confirm the existence of this bug and that the proposed fix is working nicely
